import {
  type LucideIcon,
  type LucideProps,
  Calendar,
  CalendarCheck,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Circle,
  CircleCheck,
  CircleDot,
  CircleAlert,
  Clock,
  Download,
  File,
  FileText,
  Filter,
  Inbox,
  Info,
  LayoutDashboard,
  Link as LinkIcon,
  Loader2,
  LogOut,
  Mail,
  MessageSquare,
  MoreHorizontal,
  Pencil,
  Plus,
  QrCode,
  Search,
  Send,
  Settings,
  Trash2,
  Upload,
  User,
  Users,
  UserPlus,
  X,
  AlertTriangle,
  Bell,
  Printer,
  Copy,
  Eye,
  EyeOff,
  List,
  Tag,
  ArrowRight,
  ArrowLeft,
} from "lucide-react";

// Central registry. Keep icons thin (1.5 stroke) and small by default so
// they never shout. All usage goes through <Icon name="x" /> so swapping a
// set later is a one-file change.

const map = {
  calendar: Calendar,
  "calendar-check": CalendarCheck,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  circle: Circle,
  "circle-check": CircleCheck,
  "circle-dot": CircleDot,
  "circle-alert": CircleAlert,
  clock: Clock,
  download: Download,
  file: File,
  "file-text": FileText,
  filter: Filter,
  inbox: Inbox,
  info: Info,
  dashboard: LayoutDashboard,
  link: LinkIcon,
  spinner: Loader2,
  "log-out": LogOut,
  mail: Mail,
  message: MessageSquare,
  more: MoreHorizontal,
  pencil: Pencil,
  plus: Plus,
  qr: QrCode,
  search: Search,
  send: Send,
  settings: Settings,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  "user-plus": UserPlus,
  x: X,
  warning: AlertTriangle,
  bell: Bell,
  printer: Printer,
  copy: Copy,
  eye: Eye,
  "eye-off": EyeOff,
  list: List,
  tag: Tag,
  "arrow-right": ArrowRight,
  "arrow-left": ArrowLeft,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof map;

export function Icon({
  name,
  size = 16,
  strokeWidth = 1.6,
  className,
  ...rest
}: { name: IconName } & Omit<LucideProps, "ref">) {
  const C = map[name];
  return <C size={size} strokeWidth={strokeWidth} aria-hidden className={className} {...rest} />;
}
